@AvalphaTechnologies.CommissionCalculator_HostAddress = http://localhost:5139

GET {{AvalphaTechnologies.CommissionCalculator_HostAddress}}/weatherforecast/
Accept: application/json

Get {{AvalphaTechnologies.CommissionCalculator_HostAddress}}/commission/
Accept: application/json

###
